Fixare erori

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -2,31 +2,31 @@ pipeline {
     agent any
 
     stages {
-        // stage('Clean Environment') {
-        //     steps {
-        //         script {
-        //             echo 'Cleaning up existing backend and frontend containers...'
-        //             sh '''
-        //             docker-compose -p taskflow stop backend frontend || true
-        //             docker-compose -p taskflow rm -f backend frontend || true
-        //             docker network prune -f || true
-        //             '''
-        //         }
-        //     }
-        // }
+        stage('Clean Environment') {
+            steps {
+                script {
+                    echo 'Cleaning up existing backend and frontend containers...'
+                    sh '''
+                    docker-compose -p taskflow stop backend frontend || true
+                    docker-compose -p taskflow rm -f backend frontend || true
+                    docker network prune -f || true
+                    '''
+                }
+            }
+        }
 
-        // stage('Ensure Mongo is Running') {
-        //     steps {
-        //         script {
-        //             echo 'Ensuring Mongo container is running...'
-        //             sh '''
-        //             if ! docker ps | grep -q taskflow-mongo; then
-        //                 docker start -p taskflow taskflow-mongo || docker-compose -p taskflow up -d mongo
-        //             fi
-        //             '''
-        //         }
-        //     }
-        // }
+        stage('Ensure Mongo is Running') {
+            steps {
+                script {
+                    echo 'Ensuring Mongo container is running...'
+                    sh '''
+                    if ! docker ps | grep -q taskflow-mongo; then
+                        docker start -p taskflow taskflow-mongo || docker-compose -p taskflow up -d mongo
+                    fi
+                    '''
+                }
+            }
+        }
 
         stage('Build Images') {
             steps {
@@ -71,6 +71,19 @@ pipeline {
                 }
             }
         }
+
+        stage('Quality Gate Check') {
+           steps {
+               timeout(time: 2, unit: 'MINUTES') {
+                   script {
+                       def qualityGate = waitForQualityGate()
+                       if (qualityGate.status != 'OK') {
+                           error "Pipeline failed due to Quality Gate: ${qualityGate.status}"
+                       }
+                   }
+               }
+           }
+       }
         
         stage('Deploy') {
             steps {
@@ -82,19 +95,6 @@ pipeline {
                 }
             }
         }
-
-        stage('Quality Gate Check') {
-           steps {
-               timeout(time: 5, unit: 'MINUTES') {
-                   script {
-                       def qualityGate = waitForQualityGate()
-                       if (qualityGate.status != 'OK') {
-                           error "Pipeline failed due to Quality Gate: ${qualityGate.status}"
-                       }
-                   }
-               }
-           }
-       }
     }
 
     post {
